export const mockCandidates = [
  {
    id: "1",
    name: "Alex Mercer",
    role: "Senior Frontend Engineer",
    experience: "8 years",
    match: 98,
    status: "Interviewing",
    location: "San Francisco, CA",
    avatar: "https://i.pravatar.cc/150?u=4",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "GraphQL"],
    education: "B.S. Computer Science, Stanford",
    confidence: 96,
  },
  {
    id: "2",
    name: "Samantha Lee",
    role: "Lead React Developer",
    experience: "10 years",
    match: 94,
    status: "Shortlisted",
    location: "Remote (NY)",
    avatar: "https://i.pravatar.cc/150?u=5",
    skills: ["React", "TypeScript", "Node.js", "AWS", "Redux"],
    education: "M.S. Software Engineering, MIT",
    confidence: 92,
  },
  {
    id: "3",
    name: "David Chen",
    role: "Fullstack Developer",
    experience: "5 years",
    match: 89,
    status: "Applied",
    location: "Austin, TX",
    avatar: "https://i.pravatar.cc/150?u=6",
    skills: ["Next.js", "Node.js", "TypeScript", "MongoDB", "Docker"],
    education: "B.S. Computer Science, UT Austin",
    confidence: 88,
  },
  {
    id: "4",
    name: "Elena Rodriguez",
    role: "UX/UI Designer",
    experience: "6 years",
    match: 91,
    status: "Offer Extended",
    location: "Seattle, WA",
    avatar: "https://i.pravatar.cc/150?u=3",
    skills: ["Figma", "Framer", "Prototyping", "User Research"],
    education: "B.F.A Design, RISD",
    confidence: 90,
  }
];

export const mockJobs = [
  {
    id: "j1",
    title: "Senior Frontend Engineer",
    department: "Engineering",
    applicants: 142,
    status: "Active",
    deadline: "2026-07-15",
    type: "Full-time",
    location: "San Francisco, CA / Remote",
  },
  {
    id: "j2",
    title: "Product Manager",
    department: "Product",
    applicants: 89,
    status: "Active",
    deadline: "2026-07-01",
    type: "Full-time",
    location: "New York, NY",
  },
  {
    id: "j3",
    title: "UX Designer",
    department: "Design",
    applicants: 215,
    status: "Paused",
    deadline: "2026-06-30",
    type: "Contract",
    location: "Remote",
  },
  {
    id: "j4",
    title: "DevOps Engineer",
    department: "Engineering",
    applicants: 45,
    status: "Closed",
    deadline: "2026-05-15",
    type: "Full-time",
    location: "Austin, TX",
  }
];
